#  comentarios para analizar ###########

# To interpret correspondence analysis, the first step is to evaluate whether there is a significant dependency between the rows and columns.
# 
# AAAAAAA A rigorous method is to use the chi-square statistic for examining the association between row and column variables. This appears at the top of the report generated by the function summary(res.ca) orprint(res.ca), see section @ref(r-code-to-compute-ca). A high chi-square statistic means strong link between row and column variables.
# 
# In our example, the association is highly significant (chi-square: 1944.456, p = 0).

# Chi-square statistics
chi2 <- XXXXXXXXXXXXXXXXX
# Degree of freedom
df <- (nrow(dforiginal) - 1) * (ncol(housetasks) - 1)
# P-value
pval <- pchisq(chi2, df = df, lower.tail = FALSE)
pval

# BBB Eigenvalues / Variances
# 1 Recall that, we examine the eigenvalues to determine the number of axis to be considered.
eig.val <- get_eigenvalue(res.ca)

# Eigenvalues correspond to the amount of information retained by each axis. Dimensions are ordered decreasingly and listed according to the amount of variance explained in the solution.
# Eigenvalues can be used to determine the number of axes to retain. There is no “rule of thumb” to choose the number of dimensions to keep for the data interpretation
# 2An alternative method to determine the number of dimensions is to look at a Scree Plot, which is the plot of eigenvalues/variances ordered from largest to the smallest. The number of component is determined at the point, beyond which the remaining eigenvalues are all relatively small and of comparable size.
fviz_screeplot(res.ca, addlabels = TRUE, ylim = c(0, 50))

# 3It’s also possible to calculate an average eigenvalue above which the axis should be kept in the solution.

# Our data contains 13 rows and 4 columns.
# 
# If the data were random, the expected value of the eigenvalue for each axis would be 1/(nrow(housetasks)-1) = 1/12 = 8.33% in terms of rows.
# 
# Likewise, the average axis should account for 1/(ncol(housetasks)-1) = 1/3 = 33.33% in terms of the 4 columns.
# 
# According to (M. T. Bendixen 1995):
#   
#   Any axis with a contribution larger than the maximum of these two percentages should be considered as important and included in the solution for the interpretation of the data.


fviz_screeplot(res.ca) +
  geom_hline(yintercept=XXXXX, linetype=2, color="red")

# CCCCC biplots
# 
# The graph above is called symetric plot and shows a global pattern within the data. Rows are represented by blue points and columns by red triangles.
# 
# The distance between any row points or column points gives a measure of their similarity (or dissimilarity). Row points with similar profile are closed on the factor map. The same holds true for column points.

# Symetric plot represents the row and column profiles simultaneously in a common space. In this case, only the distance between row points or the distance between column points can be really interpreted.
# 
# The distance between any row and column items is not meaningful! You can only make a general statements about the observed pattern.
# 
# In order to interpret the distance between column and row points, the column profiles must be presented in row space or vice-versa. This type of map is called asymmetric biplot and is discussed at the end of this article.

fviz_ca_biplot(res.ca, repel = TRUE)

# DDDD Contributions a las definitions


# per row
# 
# Results
# The function get_ca_row() [in factoextra] is used to extract the results for row variables. This function returns a list containing the coordinates, the cos2, the contribution and the inertia of row variables:
#   The components of the get_ca_row() function can be used in the plot of rows as follow:
#   
#   row$coord: coordinates of each row point in each dimension (1, 2 and 3). Used to create the scatter plot.
# row$cos2: quality of representation of rows.
# var$contrib: contribution of rows (in %) to the definition of the dimensions.
# Recall that, the quality of representation of the rows on the factor map is called the squared cosine (cos2) or the squared correlations.
# 
# The cos2 measures the degree of association between rows/columns and a particular axis. The cos2 of row points can be extracted as follow:
#   The values of the cos2 are comprised between 0 and 1. The sum of the cos2 for rows on all the CA dimensions is equal to one.
# 
# The quality of representation of a row or column in n dimensions is simply the sum of the squared cosine of that row or column over the n dimensions.
# You can visualize the cos2 of row points on all the dimensions using the corrplot package:


corrplot(row$cos2, is.corr=FALSE)

# Contributions of rows to the dimensions
# The contribution of rows (in %) to the definition of the dimensions can be extracted as follow:
# Rows that contribute the most to Dim.1 and Dim.2 are the most important in explaining the variability in the data set.
# Rows that do not contribute much to any dimension or that contribute to the last dimensions are less important.
#The scatter plot gives an idea of what pole of the dimensions the row categories are actually contributing to.
fviz_contrib(res.ca, choice = "row", axes = 1:2, top = 10)

fviz_ca_row(res.ca, col.row = "contrib",
            gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
            repel = TRUE)
# The red dashed line on the graph above indicates the expected average value, If the contributions were uniform. The calculation of the expected contribution value, under null hypothesis, has been detailed in the principal component analysis chapter (@ref(principal-component-analysis)).



# por columna
# The result for columns gives the same information as described for rows. For this reason, we’ll just displayed the result for columns in this section with only a very brief comment.

# biplots

# To make an asymetric biplot, rows (or columns) points are plotted from the standard co-ordinates (S) and the profiles of the columns (or the rows) are plotted from the principale coordinates (P) (M. Bendixen 2003).
# 
# For a given axis, the standard and principle co-ordinates are related as follows:
#   
#   P = sqrt(eigenvalue) X S
# 
# P: the principal coordinate of a row (or a column) on the axis
# eigenvalue: the eigenvalue of the axis
# Depending on the situation, other types of display can be set using the argument map (Nenadic and Greenacre 2007) in the function fviz_ca_biplot() [in factoextra].
# 
# The allowed options for the argument map are:
#   
#   "rowprincipal" or "colprincipal" - these are the so-called asymmetric biplots, with either rows in principal coordinates and columns in standard coordinates, or vice versa (also known as row-metric-preserving or column-metric-preserving, respectively).
# "rowprincipal": columns are represented in row space
# "colprincipal": rows are represented in column space
# "symbiplot" - both rows and columns are scaled to have variances equal to the singular values (square roots of eigenvalues), which gives a symmetric biplot but does not preserve row or column metrics.
# 
# "rowgab" or "colgab": Asymetric maps proposed by Gabriel & Odoroff (Gabriel and Odoroff 1990):
#   "rowgab": rows in principal coordinates and columns in standard coordinates multiplied by the mass.
# "colgab": columns in principal coordinates and rows in standard coordinates multiplied by the mass.
# "rowgreen" or "colgreen": The so-called contribution biplots showing visually the most contributing points (Greenacre 2006b).
# "rowgreen": rows in principal coordinates and columns in standard coordinates multiplied by square root of the mass.
# "colgreen": columns in principal coordinates and rows in standard coordinates multiplied by the square root of the mass.


# otros auxiliares

# Dimension description
#res.desc <- dimdesc(res.ca, axes = c(1,2))

# Description of dimension 2 by row points
res.desc[[2]]$row
# Description of dimension 1 by column points
res.desc[[2]]$col

# otuliers
# If one or more “outliers” are present in the contingency table, they can dominate the interpretation the axes (M. Bendixen 2003).
# 
# Outliers are points that have high absolute co-ordinate values and high contributions. They are represented, on the graph, very far from the centroïd. In this case, the remaining row/column points tend to be tightly clustered in the graph which become difficult to interpret.
# 
# In the CA output, the coordinates of row/column points represent the number of standard deviations the row/column is away from the barycentre (M. Bendixen 2003).
# 
# According to (M. Bendixen 2003):
#   
#   Outliers are points that are are at least one standard deviation away from the barycentre. They contribute also, significantly to the interpretation to one pole of an axis.
# 
# There are no apparent outliers in our data. If there were outliers in the data, they must be suppressed or treated as supplementary points when re-running the correspondence analysis.